---
# tasks file for dv_install
  - name: update registry for net install
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
      name: UseWUServer
      data: 0
      type: dword

  - name: Install .Net 3.5
    win_optional_feature:
      name: NetFx3
      state: present

  - name: create folder
    win_file:
      path: C:\ansible_temp
      state: directory

  - name: download dv packages
    win_get_url:
      url: http://{{ iph }}/dv_progs/{{ item }}
      dest: C:\ansible_temp\{{ item }}
    loop:
      - 'dvclient.msi'
      - 'dvpatch.msp'

  - name: install dv
    win_package:
      path: 'C:\ansible_temp\{{ item }}'
#      arguments: /qn allusers=1
      state: present
    become: yes
    become_method: runas
    loop:
      - 'dvclient.msi'
      - 'dvpatch.msp'

  - name: update registry for wsus au
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
      name: UseWUServer
      data: 1
      type: dword
