---
# tasks file for ../playbooks_collection/roles/fresh_install/std_progs/
  - name: Copy packages to Temp directory
    win_copy: 
      src: ./files
      dest: 'c:\ansible_temp'
#      with_fileglob: '{{ source_folder }}/*.*'
  - name: install 7Zip
    win_package:
      path: C:\ansible_temp\files\7z1900-x64.exe
      product_id: 7-Zip
      arguments: /S
      state: present
    become: yes
    become_method: runas

  - name: install acro reader DC
    win_package:
      path: C:\ansible_temp\files\AcroRdrDC1900820071_ru_RU.exe
      product_id: acrreadDC
      arguments: /S
      state: present
    become: yes
    become_method: runas

#  - name: chrome block
#    retries: 2
#    block:
  - name: install Chrome
    async: 60
    poll: 50
    win_package:
      created_path: C:\Program Files\Google\Chrome\Application\chrome.exe
      path: C:\ansible_temp\files\ChromeStandaloneSetup64.exe
      product_id: chrome
      state: present
    become: yes
    become_method: runas
    ignore_errors: yes
    register: command_result

#  - name: install firefox
#    win_package:
#      path: 'C:\ansible_temp\files\Firefox Setup 90.0.2.exe'
#      product_id: firefox
#      arguments: /S
#      state: present
#   become: yes
#    become_method: runas

#    success_when: "'FAILED' in command_result.stderr"

#      - name: check Chrome
#        win_stat:
#          path: C:\Program Files\Google\Chrome\Application
#        register: folder_info
#    when: not folder_info.stat.exist

