---
- name: install default apache web srv
  hosts: unix
  become: yes

  vars:
    source_folder: /home/oleg/unix_pb
    destin_folder: /home/oleg

  tasks:
  - name: check and print lin ver
    debug: var=ansible_os_family

  - block: #======= RH ===========

      - name: install apache for redhot
        yum: name=httpd state=latest

      - name: start web server and make enabled for rh
        service: name=httpd state=started enabled=yes
    when: ansible_os_family == "RedHat"

  - block: #========= DEB ==========

      - name: inst apache for deb
        apt: name=apache2 state=latest

      - name: start web server and make enabled for deb
        service: name=apache2 state=started enabled=yes
    when: ansible_os_family == "Debian"


  - name: copy my homepage
    copy: src={{ item }}  dest={{ destin_folder }} mode=0555
    with_fileglob: "{{ source_folder }}/*.*"
    tags: copy my homepage

#    loop:
#      - "index.html"
#      - "sea.png"
#      - "shine.png"
#      - "azure.png"

    notify: 
      - restart apache RH
      - restart apache DEB


  handlers:
  - name: restart apache RH
    service: name=httpd state=restarted
    when: ansible_os_family == "RedHat"

  - name: restart apache DEB
    service: name=apache2 state=restarted
    when: ansible_os_family == "Debian"

- name: Loops pb
  hosts: unix
  become: yes

  tasks:
  - name: say helol
    debug: msg="hello {{ item }}"
    loop:
      - "vasya"
      - "petya"
      - "mistar"

  - name: loop until ex
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output
    delay: 2
    retries: 10
    until: output.stdout.find("ZZZZZZZZZ") == false

  - name: print out finally
    debug:
      var: output.stdout

#  - name: install many pakage
#    yum: name={{ item }} state=instlled
#    loop:
#      - python
#      - tree
#      - mysql-client

